In [17]:

# No terminal, uma vez: python -m pip install openpyxl pandas
import pandas as pd
import openpyxl

In [18]:
path = r"H:\Python\3° Etapa\Analise dados\atividade4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [19]:
#Lé todas as abas do arquivo
todas = pd.read_excel(path, sheet_name=None, header=None)
print(todas.keys())

dict_keys(['Municípios'])

In [20]:
bruto = pd.read_excel(path, sheet_name="Municípios", header=None)

In [21]:
bruto

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
...,...,...,...,...,...,...,...,...
5572,NaN,DF,53,00108,Brasília,2570160,2572159,2817381
5573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5574,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5576,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
indicador = bruto.iloc[3:5573, [1,7]].copy()

indicador.columns = [
    "UF",
    "População Censo 2022",
]

indicador = indicador.reset_index(drop=True)

for col in indicador.columns[1:]:
    indicador[col] = pd.to_numeric(indicador[col], errors="coerce")

indicador

      UF  População Censo 2022
0     RO                 21494
1     RO                 96833
2     RO                  5351
3     RO                 86887
4     RO                 15890
...   ..                   ...
5565  GO                 14956
5566  GO                  8768
5567  GO                  4215
5568  GO                  5815
5569  DF               2817381

[5570 rows x 2 columns]

In [26]:
indicador_2 = bruto.iloc[3:5573, [1]].copy()

populacao_2022 = bruto.iloc[3:5573, 7]
populacao_2010 = bruto.iloc[3:5573, 5]

indicador_2["Diferença de população"] = (
    pd.to_numeric(populacao_2022, errors="coerce")
    -
    pd.to_numeric(populacao_2010, errors="coerce")
)

indicador_2.columns = [
    "UF",
    "Diferença de população",
]

indicador_2 = indicador_2.reset_index(drop=True)

for col in indicador_2.columns[1:]:
    indicador_2[col] = pd.to_numeric(indicador_2[col], errors="coerce")

indicador_2

      UF  Diferença de população
0     RO                   -2898
1     RO                    6480
2     RO                    -962
3     RO                    8313
4     RO                   -1139
...   ..                     ...
5565  GO                    2408
5566  GO                    1397
5567  GO                    -520
5568  GO                     670
5569  DF                  247221

[5570 rows x 2 columns]

In [ ]:
NOMEDODF.to_csv(r"H:\Python\3° Etapa\Analise dados\atividade4\dados.csv", sep =";")